export enum UserRole {
  CLIENT_USER = 'CLIENT_USER',
  CLIENT_ADMIN = 'CLIENT_ADMIN',
  AITEK_TEAM_MEMBER = 'AITEK_TEAM_MEMBER',
  AITEK_ADMIN = 'AITEK_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum CompanyMembershipRole {
  CLIENT_USER = 'CLIENT_USER',
  CLIENT_ADMIN = 'CLIENT_ADMIN',
}

export enum KYCStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RESUBMISSION_REQUIRED = 'RESUBMISSION_REQUIRED',
}

export enum KYCRiskLevel {
  UNSET = 'UNSET',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum KYCDocumentCategory {
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  TAX_ID = 'TAX_ID',
  GOVERNMENT_ID = 'GOVERNMENT_ID',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  NDA = 'NDA',
  OTHER = 'OTHER',
}

export enum KYCDocumentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  FLAGGED = 'FLAGGED',
}

export enum ProjectStatus {
  DISCOVERY = 'DISCOVERY',
  PLANNING = 'PLANNING',
  DESIGN = 'DESIGN',
  DEVELOPMENT = 'DEVELOPMENT',
  QA = 'QA',
  DEPLOYMENT = 'DEPLOYMENT',
  COMPLETED = 'COMPLETED',
  ON_HOLD = 'ON_HOLD',
  CANCELLED = 'CANCELLED',
}

export enum ProjectMembershipRole {
  AITEK_LEAD = 'AITEK_LEAD',
  AITEK_MEMBER = 'AITEK_MEMBER',
  CLIENT_STAKEHOLDER = 'CLIENT_STAKEHOLDER',
}

export enum MilestoneStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}

export enum OnboardingStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  ABANDONED = 'ABANDONED',
}

export enum QuestionType {
  TEXT = 'TEXT',
  LONG_TEXT = 'LONG_TEXT',
  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',
  CHECKBOX = 'CHECKBOX',
  FILE_UPLOAD = 'FILE_UPLOAD',
  BUDGET_SLIDER = 'BUDGET_SLIDER',
  TIMELINE_SELECTOR = 'TIMELINE_SELECTOR',
  RATING_SCALE = 'RATING_SCALE',
  URL_INPUT = 'URL_INPUT',
  TEAM_SIZE = 'TEAM_SIZE',
  VOICE_NOTE = 'VOICE_NOTE',
}

export enum DocumentAccessLevel {
  INTERNAL = 'INTERNAL',
  CLIENT_VISIBLE = 'CLIENT_VISIBLE',
}

export enum AgreementStatus {
  DRAFT = 'DRAFT',
  PENDING_ACKNOWLEDGMENT = 'PENDING_ACKNOWLEDGMENT',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  VIEWED = 'VIEWED',
  OVERDUE = 'OVERDUE',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
}

export enum NotificationType {
  KYC_STATUS_CHANGED = 'KYC_STATUS_CHANGED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  MILESTONE_SUBMITTED = 'MILESTONE_SUBMITTED',
  MILESTONE_APPROVED = 'MILESTONE_APPROVED',
  MILESTONE_REJECTED = 'MILESTONE_REJECTED',
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  MESSAGE_MENTION = 'MESSAGE_MENTION',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  AGREEMENT_SENT = 'AGREEMENT_SENT',
  AGREEMENT_ACKNOWLEDGED = 'AGREEMENT_ACKNOWLEDGED',
  INVOICE_CREATED = 'INVOICE_CREATED',
  ONBOARDING_COMPLETED = 'ONBOARDING_COMPLETED',
  TEAM_MEMBER_INVITED = 'TEAM_MEMBER_INVITED',
}

export enum AIOutputType {
  ONBOARDING_SUMMARY = 'ONBOARDING_SUMMARY',
  KYC_RISK_FLAGS = 'KYC_RISK_FLAGS',
  PROJECT_BRIEF = 'PROJECT_BRIEF',
  QUESTIONNAIRE_SUMMARY = 'QUESTIONNAIRE_SUMMARY',
}
